/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: 7521b1d1ecc91f684c2f1f5aebfce2f2)
interface __BaseEnv_Env {
	MCP_RATE_LIMITER: RateLimit;
	MCP_ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		MCP_RATE_LIMITER: RateLimit;
		MCP_ALLOWED_ORIGINS: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_ALLOWED_ORIGINS">> {}
}
declare module "*.mdx" {
	const value: string;
	export default value;
	}
declare module "*.md" {
	const value: string;
	export default value;
	}